Repository ember-modifier/ember-modifier, pull requests merged in 2020-07, with the labels that each got.

#38 Simplify the teardown APIs
  README.md
  addon/-private/class/modifier-manager.ts
  addon/-private/class/modifier.ts
  addon/index.ts
  tests/integration/modifiers/class-modifier-test.ts
  types/modifier-test.ts
Labels: enhancement

#41 TS: upgrade to 3.9; implement RFC for type stability
  .gitignore
  config/ember-try-typescript.js
  package.json
  tsconfig.json
  type-tests/modifier-test.ts
  type-tests/tsconfig-3.6.json
  type-tests/tsconfig-3.7.json
  type-tests/tsconfig-downlevel.json
  type-tests/tsconfig-next.json
  yarn.lock
Labels: enhancement

#45 Remove module unification support from blueprints
  blueprints/modifier-test/index.js
  blueprints/modifier/index.js
  blueprints/modifier/mu_files/__root__/__collection__/__name__.js
  blueprints/module-unification.js
Labels: breaking

#46 Use ember-cli-htmlbars for inline precompilation.
  blueprints/modifier-test/index.js
  blueprints/modifier-test/mocha-files/__root__/integration/__collection__/__name__-test.js
  blueprints/modifier-test/qunit-files/__root__/integration/__collection__/__name__-test.js
  package.json
  tests/integration/modifiers/class-modifier-test.ts
  tests/integration/modifiers/functional-modifier-test.ts
  yarn.lock
Labels: enhancement

#47 Update addon blueprint from v3.13 to v3.20
  .editorconfig
  .eslintrc.js
  .travis.yml
  CONTRIBUTING.md
  README.md
  config/ember-try.js
  package.json
  testem.js
  tests/dummy/app/app.js
  tests/dummy/app/resolver.js
  tests/dummy/app/router.js
  tests/dummy/app/templates/components/.gitkeep
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/optional-features.json
  tests/dummy/config/targets.js
  tests/integration/modifiers/class-modifier-test.ts
  tests/test-helper.js
  yarn.lock
Labels: internal

#48 Migrate to @ember/destroyable for destruction.
  addon/-private/class/modifier-manager.ts
  addon/-private/class/modifier.ts
  addon/-private/utils/symbol.ts
  package.json
  tests/integration/modifiers/class-modifier-test.ts
  tsconfig.json
  types/ember-private/index.d.ts
  yarn.lock
Labels: bug

#49 Refactor / cleanup owner usage in Modifier manager APIs.
  addon/-private/class/modifier-manager.ts
  addon/-private/class/modifier.ts
  addon/-private/functional/modifier-manager.ts
  addon/-private/functional/modifier.ts
Labels: internal

#51 Add v3.20 to v1.x's CI configuration
  .travis.yml
Labels: internal

#54 Update dependencies to fix issues with `@ember/destroyable`.
  package.json
  yarn.lock
Labels: bug
