Repository ember-modifier/ember-modifier, pull requests merged in 2020-05, with the labels that each got.

#23 Convert the addon to TypeScript
  README.md
  addon/-private/class/modifier-manager.js
  addon/-private/class/modifier-manager.ts
  addon/-private/class/modifier.js
  addon/-private/class/modifier.ts
  addon/-private/functional/modifier-manager.ts
  addon/-private/functional/modifier.js
  addon/-private/functional/modifier.ts
  addon/-private/interfaces.ts
  addon/-private/utils/symbol.ts
  addon/index.js
  addon/index.ts
  package.json
  tests/dummy/app/config/environment.d.ts
  tests/integration/modifiers/class-modifier-test.js
  tests/integration/modifiers/class-modifier-test.ts
  tests/integration/modifiers/functional-modifier-test.js
  tests/integration/modifiers/functional-modifier-test.ts
  tsconfig.json
  types/@ember/modifier/index.d.ts
  types/dummy/index.d.ts
  types/ember-private/index.d.ts
  types/modifier-test.ts
  yarn.lock
Labels: enhancement

#31 Drop support for Node 8 and 9
  .travis.yml
  package.json
Labels: breaking

#16 Use release-it and lerna-changelog to manage releases
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#30 Support linting TS, and test types
  .eslintrc.js
  .travis.yml
  .vscode/settings.json
  addon/-private/class/modifier-manager.ts
  addon/-private/class/modifier.ts
  addon/-private/functional/modifier-manager.ts
  addon/-private/functional/modifier.ts
  addon/-private/utils/symbol.ts
  blueprints/.eslintrc.js
  blueprints/modifier-test/index.js
  blueprints/modifier/index.js
  blueprints/test-framework-detector.js
  config/ember-try-typescript.js
  config/ember-try.js
  ember-cli-build.js
  package.json
  tests/dummy/app/config/environment.d.ts
  tests/dummy/app/router.js
  tests/dummy/config/environment.js
  tests/integration/modifiers/class-modifier-test.ts
  tests/integration/modifiers/functional-modifier-test.ts
  yarn.lock
Labels: internal
