Repository ember-modifier/ember-modifier, pull requests merged in 2022-03, with the labels that each got.

#209 Update to latest `@types/ember(*)` and `@types/qunit`
  .template-lintrc.js
  addon/-private/compat.ts
  package.json
  tests/integration/modifiers/class-modifier-test.ts
  tests/integration/modifiers/functional-modifier-test.ts
  yarn.lock
Labels: dependencies

#212 Deprecate `willDestroy()` and `isDestroy(ing|ed)`
  addon/-private/class/modifier.ts
Labels: enhancement

#219 Add ':no_entry_sign: Deprecations' to lerna config
  package.json
Labels: internal

#217 Introduce new `modify` hook
  addon/-private/class/modifier-manager.ts
  addon/-private/class/modifier.ts
  addon/-private/compat.ts
  addon/-private/signature.ts
  tests/integration/modifiers/class-modifier-test.ts
  tsconfig.json
Labels: enhancement

#220 Deprecate didInstall, didReceiveArguments, and didUpdateArguments
  addon/-private/class/modifier.ts
Labels: deprecation

#221 Deprecate `this.element` and `this.args` on class-based modifiers
  addon/-private/class/modifier-manager.ts
  addon/-private/class/modifier.ts
Labels: deprecation

#222 Introduce `eager` option to function-based modifiers
  addon/-private/functional/modifier-manager.ts
  addon/-private/functional/modifier.ts
  addon/-private/signature.ts
  tests/integration/modifiers/functional-modifier-test.ts
  type-tests/modifier-test.ts
Labels: enhancement

#226 Upgrade to latest @types for @ember/modifier
  package.json
  types/@ember/modifier/index.d.ts
  yarn.lock
Labels: internal

#223 Deprecate `modifier()` without `{ eager: false }`
  addon/-private/functional/modifier.ts
Labels: deprecation

#227 Update docs and export type utils
  MIGRATIONS.md
  README.md
  addon/-private/signature.ts
  addon/index.ts
Labels: documentation

#230 Solidify types for release
  addon/-private/class/modifier.ts
  addon/-private/function-based/modifier-manager.ts
  addon/-private/function-based/modifier.ts
  addon/-private/interfaces.ts
  addon/-private/opaque.ts
  addon/index.ts
  type-tests/modifier-test.ts
Labels: enhancement

#231 Don't commit generated .d.ts files
  -private/class/modifier-manager.d.ts
  -private/class/modifier.d.ts
  -private/compat.d.ts
  -private/function-based/modifier-manager.d.ts
  -private/function-based/modifier.d.ts
  -private/interfaces.d.ts
  -private/opaque.d.ts
  -private/signature.d.ts
  .gitignore
  index.d.ts
Labels: internal

#234 Include 3.2 deprecations in CHANGELOG
  CHANGELOG.md
Labels: internal

#237 Update README for v4 development
  README.md
Labels: documentation

#238 Drop support for Node 12
  .github/workflows/ci.yml
  package.json
Labels: breaking

#245 Update Class-based modifier example
  README.md
Labels: documentation

#244 Remove all deprecations targeting v4
  addon/-private/class/modifier-manager.ts
  addon/-private/class/modifier.ts
  addon/-private/compat.ts
  addon/-private/function-based/modifier-manager.ts
  addon/-private/function-based/modifier.ts
  addon/-private/interfaces.ts
  addon/-private/signature.ts
  addon/index.ts
  tests/integration/modifiers/class-modifier-test.ts
  tests/integration/modifiers/functional-modifier-test.ts
  type-tests/modifier-test.ts
Labels: breaking

#252 Invert deprecation for missing options
  addon/-private/function-based/modifier.ts
Labels: bug

#253 Check type of teardown before saving or using it
  addon/-private/function-based/modifier-manager.ts
Labels: bug
