Repository ember-modifier/ember-modifier, pull requests merged in 2022-04, with the labels that each got.

#261 Add tests for unions in legacy args form
  type-tests/modifier-test.ts
Labels: internal

#278 Make `FunctionBasedModifier` an (abstract) constructor type
  addon/-private/function-based/modifier.ts
  tests/integration/modifiers/functional-modifier-test.ts
  type-tests/modifier-test.ts
Labels: bug

#280 Use "export type" for FunctionBasedModifier interface
  addon/index.ts
Labels: bug

#283 Fix deprecations for class-based modifiers
  addon/-private/class/modifier.ts
Labels: bug

#318 Use 'class-based' instead of 'class' in layout
  addon/src/-private/class-based/modifier-manager.ts
  addon/src/-private/class-based/modifier.ts
  addon/src/-private/function-based/modifier.ts
  addon/src/index.ts
Labels: internal

#326 Fix `watchDependencies` usage
  addon/rollup.config.js
  test-app/ember-cli-build.js
Labels: internal

#329 The package must be public
  addon/package.json
  package.json
  test-app/package.json
Labels: internal

#328 run `npx ember-cli-update --to=4.3.0` to align with blueprint
  .gitignore
  addon/.gitignore
  addon/README.md
  package.json
  test-app/.ember-cli
  test-app/.gitignore
  test-app/README.md
  test-app/app/index.html
  test-app/config/ember-cli-update.json
  test-app/config/environment.js
  test-app/package.json
  test-app/tests/helpers/.gitkeep
  test-app/tests/helpers/index.js
  test-app/tests/index.html
  test-app/tests/test-helper.js
  test-app/tsconfig.json
  test-app/types/test-app/index.d.ts
  yarn.lock
Labels: internal

#330 add `@types/ember__destroyable`
  addon/package.json
  addon/tsconfig.json
  package.json
  yarn.lock
Labels: dependencies
