Repository ember-modifier/ember-modifier, pull requests merged in 2023-02, with the labels that each got.

#662 Use tilde instead of caret for rollup-plugin-ts
  addon/package.json
  yarn.lock
Labels: dependencies

#683 Support Ember v5
  addon/src/-private/class-based/modifier-manager.ts
  addon/src/-private/function-based/modifier-manager.ts
  test-app/config/ember-try.js
  test-app/ember-cli-build.js
  test-app/package.json
  yarn.lock
Labels: enhancement

#665 Use the types published from Ember itself
  .github/workflows/ci.yml
  addon/package.json
  addon/tsconfig.json
  addon/unpublished-development-types/index.d.ts
  test-app/config/ember-try.js
  test-app/package.json
  test-app/types/test-app/index.d.ts
  yarn.lock
Labels: enhancement

#686 Rename addon folder to ember-modifier
  .github/workflows/ci.yml
  .github/workflows/publish-unstable.yml
  CONTRIBUTING.md
  ember-modifier/.eslintignore
  ember-modifier/.eslintrc.js
  ember-modifier/.gitignore
  ember-modifier/.prettierignore
  ember-modifier/.prettierrc.js
  ember-modifier/addon-main.js
  ember-modifier/babel.config.json
  ember-modifier/blueprints/modifier-test/index.js
  ember-modifier/blueprints/modifier-test/mocha-files/__root__/integration/__collection__/__name__-test.js
  ember-modifier/blueprints/modifier-test/qunit-files/__root__/integration/__collection__/__name__-test.js
  ember-modifier/blueprints/modifier/files/__root__/__collection__/__name__.js
  ember-modifier/blueprints/modifier/index.js
  ember-modifier/blueprints/test-framework-detector.js
  ember-modifier/package.json
  ember-modifier/rollup.config.mjs
  ember-modifier/src/-private/class-based/modifier-manager.ts
  ember-modifier/src/-private/class-based/modifier.ts
  ember-modifier/src/-private/function-based/modifier-manager.ts
  ember-modifier/src/-private/function-based/modifier.ts
  ember-modifier/src/-private/opaque.ts
  ember-modifier/src/-private/signature.ts
  ember-modifier/src/index.ts
  ember-modifier/tsconfig.json
  ember-modifier/type-tests/modifier-test.ts
  ember-modifier/unpublished-development-types/index.d.ts
  package.json
Labels: internal

#687 Remove engines field from addon package.json
  .github/workflows/ci.yml
  .github/workflows/publish-unstable.yml
  README.md
  ember-modifier/package.json
  package.json
Labels: enhancement

#688 Add TypeScript 4.8 and 4.9 to test matrix
  .github/workflows/ci.yml
  README.md
  ember-modifier/package.json
  test-app/config/ember-try.js
  test-app/package.json
  yarn.lock
Labels: dependencies
